version: "3.9"
services:
  heat_trans:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: heat_trans
    ports:
      - '3000:3000' # dev build
    volumes:
      - .:/srv/
      - /srv/node_modules
    tty: true
